import { IFormChecksValues } from "./interfaces";

export const initialValues: IFormChecksValues = {
  modifyDosis: false,
  dosification: false,
  adminPuat: false,
  addMed: false,
  resMed: false,
  susMed: false,
  educateMed: false,
  modifyApt: false,
  educateMedities: false,
  remMed: false,
  medicalProbleNotTrated: false,
  medicalEfectInnecesary: false,
  inefectivityNoct: false,
  inefectivityyCt: false,
  insegurityNoCt: false,
  insegurityCt: false,
  interactionFarmaco: false,
  duplicityFarmaco: false,
  quantityMedSolicityNoCtD: false,
  sobredosification: false,
  subDosification: false,
  writedToPatient: false,
  writedToMed: false,
  acepted: false,
  noAcepted: false,
  ejecuted: false,
  noEjecuted: false,
};
