export interface IFormChecksValues {
  modifyDosis: boolean;
  dosification: boolean;
  adminPuat: boolean;
  addMed: boolean;
  resMed: boolean;
  susMed: boolean;
  educateMed: boolean;
  modifyApt: boolean;
  educateMedities: boolean;
  remMed: boolean;
  medicalProbleNotTrated: boolean;
  medicalEfectInnecesary: boolean;
  inefectivityNoct: boolean;
  inefectivityyCt: boolean;
  insegurityNoCt: boolean;
  insegurityCt: boolean;
  interactionFarmaco: boolean;
  duplicityFarmaco: boolean;
  quantityMedSolicityNoCtD: boolean;
  sobredosification: boolean;
  subDosification: boolean;
  writedToPatient: boolean;
  writedToMed: boolean;
  acepted: boolean;
  noAcepted: boolean;
  ejecuted: boolean;
  noEjecuted: boolean;
}
